version: 0.2
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/classes/* .
      - rm -rf target src buildspec.yml pom.xml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-1-174632319992 --output-template NewSamTemplate.yaml

artifacts:
  type: jar
  files:
    - NewSamTemplate.yaml
