version: 0.2
phases:
  post_build:
    commands:
      - mvn clean package
      - mv target/classes/* .
      - rm -rf target src buildspec.yml pom.xml
      - aws cloudformation package --template-file samTemplate.yaml --kms-key-id arn:aws:kms:us-east-1:421775237038:key/d91b925c-8a3b-400c-ae49-9122b1f7b85e --s3-bucket codepipeline-us-east-1-432104467414 --output-template NewSamTemplate.yaml
      
artifacts:
  type: jar
  files:
    - NewSamTemplate.yaml
