version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - aws cloudformation package --template-file samTemplate.yaml --kms-key-id arn:aws:kms:us-east-1:491398371152:key/aa8461d2-467d-431a-a544-9b0620f276ec --s3-bucket demo5550 --output-template NewSamTemplate.yaml

artifacts:
  type: jar
  files:
    - '**/*'
    - NewSamTemplate.yaml
  discard-paths: yes
