version: 0.2
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/classes/* .
      - rm -rf target src buildspec.yml pom.xml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-1-432104467414 --kms-key-id arn:aws:kms:us-east-1:491398371152:key/aa8461d2-467d-431a-a544-9b0620f276ec --output-template NewSamTemplate.yaml

artifacts:
  type: jar
  files:
    - NewSamTemplate.yaml
