version: 0.2
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-1-174632319992/JavaPipeline/MyAppBuild --output-template NewSamTemplate.yaml

artifacts:
  type: jar
  files:
    - NewSamTemplate.yaml
    - lambda-1.0.jar