version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package --template-file samTemplate.yaml --s3-bucket demo-pipeline-1 --output-template-file NewSamTemplate.yaml
artifacts:
  type: jar
  files:
    -helloWorld.jar
  discard-paths: yes