AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello world function
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'target.classes.com.example.lambda.demo.Hello::handleRequest'
      Runtime: java8
      CodeUri: ./
      Events:
        MyJavaApi:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
